from pyspark.sql import SparkSession, DataFrame
from pyspark.sql import functions as F
from pyspark.sql.types import LongType
import uuid
import os
os.environ["HADOOP_HOME"] = r"C:\hadoop"
os.environ["PATH"] = os.environ["PATH"] + r";C:\hadoop\bin"

# -------------------------
# SPARK SESSION
# -------------------------

def get_spark(app_name: str = "ecommerce_etl") -> SparkSession:
    """
    Get or create a local SparkSession.
    In production, remove the master("local[*]") line and let the
    cluster config inject it via spark-submit.
    """
    return (
        SparkSession.builder
        .appName(app_name)
        .master("local[*]")
        .config("spark.jars", r"C:\Program Files\PostgreSQL\postgresql-42.7.11.jar")
        .getOrCreate()
    )

# -------------------------
# EXTRACT
# -------------------------

def extract_orders(spark: SparkSession, filepath: str) -> DataFrame:
    """
    Read orders CSV and cast ID columns to LongType (nullable).

    Args:
        spark: Active SparkSession.
        filepath: Path to the orders CSV file.

    Returns:
        Spark DataFrame with customer_id, product_id, order_id as Long.
    """
    df = spark.read.csv(filepath, header=True, inferSchema=False)

    for col in ("customer_id", "product_id", "order_id"):
        df = df.withColumn(col, F.col(col).cast("double").cast(LongType()))

    df = df.withColumn("quantity", F.col("quantity").cast("integer"))
    df = df.withColumn("unit_price", F.col("unit_price").cast("double"))
    df = df.withColumn("order_date", F.to_date("order_date", "yyyy-MM-dd"))

    return df

def extract_customers(spark: SparkSession, jdbc_url: str, jdbc_props: dict) -> DataFrame:
    """
    Pull customer_id, customer_tier, and country from the OLTP DB via JDBC.
    Args:
        spark:      Active SparkSession.
        jdbc_url:   JDBC connection string.
        jdbc_props: Dict with 'user', 'password', 'driver'.
    Returns:
        Spark DataFrame with columns: customer_id, customer_tier, country.
    """
    return spark.read.jdbc(
        url=jdbc_url,
        table="(SELECT customer_id, customer_tier, country FROM customers) t",
        properties=jdbc_props,
    )

def extract_products(spark: SparkSession, jdbc_url: str, jdbc_props: dict) -> DataFrame:
    """
    Pull product_id, category, and unit_cost from the OLTP DB via JDBC.
    Args:
        spark:      Active SparkSession.
        jdbc_url:   JDBC connection string.
        jdbc_props: Dict with 'user', 'password', 'driver'.

    Returns:
        Spark DataFrame with columns: product_id, category, unit_cost.
    """
    return spark.read.jdbc(
        url=jdbc_url,
        table="(SELECT product_id, category, unit_cost FROM products) t",
        properties=jdbc_props,
    )

# -------------------------
# TRANSFORM
# -------------------------

# Fields that must be non-null for a row to be valid
_CRITICAL_FIELDS = ("order_item_id", "order_id", "order_date", "customer_id", "product_id")


def transform(
    orders: DataFrame,
    customers: DataFrame,
    products: DataFrame,
    etl_run_id: str,
) -> DataFrame:
    """
    Join orders with customers and products, clean, deduplicate, compute
    revenue/margin fields, and enforce a final column order.

    Cleaning steps (applied before any computation):
      1. Drop rows where any critical field (order_item_id, order_id,
         order_date, customer_id, product_id) is NULL.
      2. Drop rows with quantity <= 0 or unit_price <= 0.
      3. Deduplicate on order_item_id, keeping the first occurrence after
         ordering by order_id descending (latest wins on re-delivery).

    Args:
        orders:      Output of extract_orders().
        customers:   Output of extract_customers().
        products:    Output of extract_products().
        etl_run_id:  UUID string generated by run_pipeline(); shared with
                     load.py so fact rows and audit log carry the same ID.

    Returns:
        Cleaned, enriched Spark DataFrame ready for write_parquet().
    """
    from pyspark.sql.window import Window

    # --- 1. Drop nulls on critical fields ---
    null_filter = F.col(_CRITICAL_FIELDS[0]).isNotNull()
    for field in _CRITICAL_FIELDS[1:]:
        null_filter = null_filter & F.col(field).isNotNull()

    # --- 2. Drop non-positive quantity / price ---
    clean = (
        orders
        .filter(null_filter)
        .filter(F.col("quantity") > 0)
        .filter(F.col("unit_price") > 0)
    )

    # --- 3. Deduplicate on order_item_id (keep latest by order_id) ---
    window = Window.partitionBy("order_item_id").orderBy(F.col("order_id").desc())
    clean = (
        clean
        .withColumn("_row_num", F.row_number().over(window))
        .filter(F.col("_row_num") == 1)
        .drop("_row_num")
    )

    # --- 4. Joins + computed columns ---
    fact = (
        clean
        .join(F.broadcast(customers), on="customer_id", how="left")
        .join(F.broadcast(products),  on="product_id",  how="left")
        .withColumnRenamed("country",  "customer_country")
        .withColumnRenamed("category", "product_category")
        .withColumn(
            "gross_revenue",
            F.round(F.col("quantity") * F.col("unit_price"), 2)
        )
        .withColumn(
            "gross_margin",
            F.round(F.col("quantity") * (F.col("unit_price") - F.col("unit_cost")), 2)
        )
        .withColumn(
            "margin_pct",
            F.when(
                F.col("gross_revenue") == 0,
                F.lit(None).cast("double")
            ).otherwise(
                F.round((F.col("gross_margin") / F.col("gross_revenue")) * 100, 2)
            )
        )
        .withColumn("etl_run_id", F.lit(etl_run_id))
        .select(
            "order_item_id",
            "order_id",
            "order_date",
            "customer_id",
            "customer_tier",
            "customer_country",
            "product_id",
            "product_category",
            "quantity",
            "unit_price",
            "unit_cost",
            "gross_revenue",
            "gross_margin",
            "margin_pct",
            "channel",
            "etl_run_id",
        )
    )

    return fact

# -------------------------
# DIAGNOSTICS
# -------------------------

def log_quality(fact: DataFrame) -> None:
    """Print basic data quality counts to stdout."""
    total = fact.count()
    missing_customer = fact.filter(F.col("customer_tier").isNull()).count()
    missing_product = fact.filter(F.col("product_category").isNull()).count()

    print(f"\nDataset shape: {total} rows x {len(fact.columns)} columns")
    print(f"Missing customer matches: {missing_customer}")
    print(f"Missing product matches:  {missing_product}")
    fact.show(5, truncate=False)

# -------------------------
# WRITE PARQUET
# -------------------------

def write_parquet(fact: DataFrame, partition_date: str, base_path: str = "data/processed") -> dict:
    """
    Write the transformed fact DataFrame and its daily summary to Parquet.

    Outputs two directories under base_path/dt=YYYY-MM-DD/:
      - fact/       — one row per order line item
      - summary/    — daily_category_sales grain

    Partitioned files make each step independently re-runnable: the load
    step reads from Parquet rather than holding the DataFrame in memory.

    Args:
        fact:           Output of transform().
        partition_date: 'YYYY-MM-DD' string used as the directory name.
        base_path:      Root directory for processed output (default: data/processed).

    Returns:
        Dict with keys 'fact_path' and 'summary_path'.
    """
    from pyspark.sql import functions as F

    fact_path    = f"{base_path}/dt={partition_date}/fact"
    summary_path = f"{base_path}/dt={partition_date}/summary"

    # Fact table
    (
        fact.write
        .mode("overwrite")
        .parquet(fact_path)
    )
    print(f"[write_parquet] Fact written to {fact_path}")

    # Daily summary — reuse the same aggregation logic as load.py
    summary = (
        fact
        .groupBy("order_date", "product_category", "customer_country")
        .agg(
            F.countDistinct("order_id").alias("order_count"),
            F.sum("quantity").cast("integer").alias("units_sold"),
            F.round(F.sum("gross_revenue"), 2).alias("gross_revenue"),
            F.round(F.sum("gross_margin"), 2).alias("gross_margin"),
            F.round(F.avg("gross_revenue"), 2).alias("avg_order_value"),
        )
        .withColumnRenamed("order_date", "summary_date")
    )

    (
        summary.write
        .mode("overwrite")
        .parquet(summary_path)
    )
    print(f"[write_parquet] Summary written to {summary_path}")

    return {"fact_path": fact_path, "summary_path": summary_path}



# -------------------------
# ORCHESTRATOR
# -------------------------

def run_pipeline(
    orders_filepath: str,
    oltp_host: str = "localhost",
    oltp_db: str = "ecommerce_oltp",
    oltp_user: str = "postgres",
    oltp_password: str = "admin",
    oltp_port: str = "5432",
    dw_host: str = "localhost",
    dw_db: str = "ecommerce_dw",
    dw_user: str = "postgres",
    dw_password: str = "admin",
    dw_port: str = "5432",
    dw_table: str = "fact_order_items",
    dag_id: str = "manual",
    processed_base: str = "data/processed",
) -> DataFrame:
    """
    Full ETL run: extract → transform → write Parquet → load → validate.

    The run_id is generated here and flows through transform(), write_parquet(),
    and load.run_all_loads() so every fact row, summary row, and audit log
    entry share the same identifier.

    The partition date is parsed from the filepath (expects dt=YYYY-MM-DD in
    the directory path, e.g. data/raw/dt=2026-06-01/orders.csv).

    Args:
        orders_filepath: Path to the orders CSV.
        oltp_*:          Connection parameters for the OLTP Postgres database.
        dw_*:            Connection parameters for the warehouse Postgres database.
        dag_id:          Airflow DAG ID or 'manual' for local runs.
        processed_base:  Root path for Parquet output (default: data/processed).

    Returns:
        Transformed Spark DataFrame (also persisted to Parquet and warehouse).
    """
    import re
    from load import run_all_loads

    spark = get_spark()

    # --- Partition date ---
    match = re.search(r"dt=(\d{4}-\d{2}-\d{2})", orders_filepath)
    partition_date = match.group(1) if match else None
    if not partition_date:
        raise ValueError(
            f"Cannot parse partition date from filepath: {orders_filepath}. "
            "Expected a dt=YYYY-MM-DD directory component."
        )
    print(f"\nPartition date: {partition_date}")

    # --- Single run_id for the entire pipeline run ---
    run_id = str(uuid.uuid4())
    print(f"ETL run ID: {run_id}")

    # --- Connection params ---
    oltp_jdbc_url = f"jdbc:postgresql://{oltp_host}:{oltp_port}/{oltp_db}"
    oltp_jdbc_props = {
        "user": oltp_user,
        "password": oltp_password,
        "driver": "org.postgresql.Driver",
    }

    dw_jdbc_url = f"jdbc:postgresql://{dw_host}:{dw_port}/{dw_db}"
    dw_jdbc_props = {
        "user": dw_user,
        "password": dw_password,
        "driver": "org.postgresql.Driver",
    }
    dw = {
        "host": dw_host,
        "port": dw_port,
        "db": dw_db,
        "user": dw_user,
        "password": dw_password,
    }

    # --- Extract ---
    orders    = extract_orders(spark, orders_filepath)
    customers = extract_customers(spark, oltp_jdbc_url, oltp_jdbc_props)
    products  = extract_products(spark, oltp_jdbc_url, oltp_jdbc_props)

    # --- Transform ---
    fact = transform(orders, customers, products, etl_run_id=run_id)
    log_quality(fact)

    # --- Write Parquet (decouple transform from load) ---
    parquet_paths = write_parquet(fact, partition_date, base_path=processed_base)

    # --- Load + Validate (reads from Parquet, not in-memory DataFrame) ---
    run_all_loads(
        spark=spark,
        fact_path=parquet_paths["fact_path"],
        summary_path=parquet_paths["summary_path"],
        jdbc_url=dw_jdbc_url,
        jdbc_props=dw_jdbc_props,
        dw=dw,
        partition_date=partition_date,
        etl_run_id=run_id,
        dag_id=dag_id,
    )

    return fact

# -------------------------
# ENTRY POINT
# -------------------------

if __name__ == "__main__":
    run_pipeline("data/raw/dt=2026-06-01/orders.csv")